/**
 * NAKSHATRA LOOKUP TABLE
 * 27 Nakshatras with all Ashta Koota attributes
 * Each Nakshatra spans 13°20' (13.333...°) of the zodiac
 */

const NAKSHATRAS = [
   // index 0-26
   {
      index: 0,
      name: "Ashwini",
      symbol: "🐴",
      animal: "Horse",
      animalGender: "Male",
      rashi: "Aries",
      rashiIndex: 0,
      lord: "Ketu",
      lordIndex: 6,
      gana: "Deva", // Deva / Manushya / Rakshasa
      varna: "Vaishya", // Brahmin / Kshatriya / Vaishya / Shudra
      nadi: "Vata", // Vata / Pitta / Kapha
      vashya: "Chatushpad", // Manav / Chatushpad / Jalchar / Vanchar / Keeta
   },
   {
      index: 1,
      name: "Bharani",
      symbol: "🐘",
      animal: "Elephant",
      animalGender: "Male",
      rashi: "Aries",
      rashiIndex: 0,
      lord: "Venus",
      lordIndex: 5,
      gana: "Manushya",
      varna: "Shudra",
      nadi: "Pitta",
      vashya: "Manav",
   },
   {
      index: 2,
      name: "Krittika",
      symbol: "🐏",
      animal: "Sheep",
      animalGender: "Female",
      rashi: "Taurus",
      rashiIndex: 1,
      lord: "Sun",
      lordIndex: 0,
      gana: "Rakshasa",
      varna: "Brahmin",
      nadi: "Kapha",
      vashya: "Chatushpad",
   },
   {
      index: 3,
      name: "Rohini",
      symbol: "🐍",
      animal: "Serpent",
      animalGender: "Male",
      rashi: "Taurus",
      rashiIndex: 1,
      lord: "Moon",
      lordIndex: 1,
      gana: "Manushya",
      varna: "Shudra",
      nadi: "Kapha",
      vashya: "Chatushpad",
   },
   {
      index: 4,
      name: "Mrigashira",
      symbol: "🐍",
      animal: "Serpent",
      animalGender: "Female",
      rashi: "Gemini",
      rashiIndex: 2,
      lord: "Mars",
      lordIndex: 3,
      gana: "Deva",
      varna: "Vaishya",
      nadi: "Pitta",
      vashya: "Manav",
   },
   {
      index: 5,
      name: "Ardra",
      symbol: "🐕",
      animal: "Dog",
      animalGender: "Female",
      rashi: "Gemini",
      rashiIndex: 2,
      lord: "Rahu",
      lordIndex: 7,
      gana: "Manushya",
      varna: "Shudra",
      nadi: "Vata",
      vashya: "Manav",
   },
   {
      index: 6,
      name: "Punarvasu",
      symbol: "🐱",
      animal: "Cat",
      animalGender: "Female",
      rashi: "Cancer",
      rashiIndex: 3,
      lord: "Jupiter",
      lordIndex: 4,
      gana: "Deva",
      varna: "Vaishya",
      nadi: "Vata",
      vashya: "Manav",
   },
   {
      index: 7,
      name: "Pushya",
      symbol: "🐏",
      animal: "Sheep",
      animalGender: "Male",
      rashi: "Cancer",
      rashiIndex: 3,
      lord: "Saturn",
      lordIndex: 8,
      gana: "Deva",
      varna: "Kshatriya",
      nadi: "Pitta",
      vashya: "Manav",
   },
   {
      index: 8,
      name: "Ashlesha",
      symbol: "🐱",
      animal: "Cat",
      animalGender: "Male",
      rashi: "Cancer",
      rashiIndex: 3,
      lord: "Mercury",
      lordIndex: 2,
      gana: "Rakshasa",
      varna: "Shudra",
      nadi: "Kapha",
      vashya: "Keeta",
   },
   {
      index: 9,
      name: "Magha",
      symbol: "🐀",
      animal: "Rat",
      animalGender: "Male",
      rashi: "Leo",
      rashiIndex: 4,
      lord: "Ketu",
      lordIndex: 6,
      gana: "Rakshasa",
      varna: "Shudra",
      nadi: "Vata",
      vashya: "Vanchar",
   },
   {
      index: 10,
      name: "Purva Phalguni",
      symbol: "🐀",
      animal: "Rat",
      animalGender: "Female",
      rashi: "Leo",
      rashiIndex: 4,
      lord: "Venus",
      lordIndex: 5,
      gana: "Manushya",
      varna: "Brahmin",
      nadi: "Pitta",
      vashya: "Vanchar",
   },
   {
      index: 11,
      name: "Uttara Phalguni",
      symbol: "🐄",
      animal: "Cow",
      animalGender: "Female",
      rashi: "Virgo",
      rashiIndex: 5,
      lord: "Sun",
      lordIndex: 0,
      gana: "Manushya",
      varna: "Kshatriya",
      nadi: "Kapha",
      vashya: "Manav",
   },
   {
      index: 12,
      name: "Hasta",
      symbol: "🐃",
      animal: "Buffalo",
      animalGender: "Female",
      rashi: "Virgo",
      rashiIndex: 5,
      lord: "Moon",
      lordIndex: 1,
      gana: "Deva",
      varna: "Vaishya",
      nadi: "Vata",
      vashya: "Manav",
   },
   {
      index: 13,
      name: "Chitra",
      symbol: "🐅",
      animal: "Tiger",
      animalGender: "Female",
      rashi: "Libra",
      rashiIndex: 6,
      lord: "Mars",
      lordIndex: 3,
      gana: "Rakshasa",
      varna: "Vaishya",
      nadi: "Pitta",
      vashya: "Manav",
   },
   {
      index: 14,
      name: "Swati",
      symbol: "🐃",
      animal: "Buffalo",
      animalGender: "Male",
      rashi: "Libra",
      rashiIndex: 6,
      lord: "Rahu",
      lordIndex: 7,
      gana: "Deva",
      varna: "Shudra",
      nadi: "Kapha",
      vashya: "Manav",
   },
   {
      index: 15,
      name: "Vishakha",
      symbol: "🐅",
      animal: "Tiger",
      animalGender: "Male",
      rashi: "Scorpio",
      rashiIndex: 7,
      lord: "Jupiter",
      lordIndex: 4,
      gana: "Rakshasa",
      varna: "Shudra",
      nadi: "Kapha",
      vashya: "Manav",
   },
   {
      index: 16,
      name: "Anuradha",
      symbol: "🦌",
      animal: "Deer",
      animalGender: "Female",
      rashi: "Scorpio",
      rashiIndex: 7,
      lord: "Saturn",
      lordIndex: 8,
      gana: "Deva",
      varna: "Shudra",
      nadi: "Pitta",
      vashya: "Keeta",
   },
   {
      index: 17,
      name: "Jyeshtha",
      symbol: "🦌",
      animal: "Deer",
      animalGender: "Male",
      rashi: "Scorpio",
      rashiIndex: 7,
      lord: "Mercury",
      lordIndex: 2,
      gana: "Rakshasa",
      varna: "Vaishya",
      nadi: "Vata",
      vashya: "Keeta",
   },
   {
      index: 18,
      name: "Mula",
      symbol: "🐕",
      animal: "Dog",
      animalGender: "Male",
      rashi: "Sagittarius",
      rashiIndex: 8,
      lord: "Ketu",
      lordIndex: 6,
      gana: "Rakshasa",
      varna: "Kshatriya",
      nadi: "Kapha",
      vashya: "Vanchar",
   },
   {
      index: 19,
      name: "Purva Ashadha",
      symbol: "🐒",
      animal: "Monkey",
      animalGender: "Male",
      rashi: "Sagittarius",
      rashiIndex: 8,
      lord: "Venus",
      lordIndex: 5,
      gana: "Manushya",
      varna: "Brahmin",
      nadi: "Pitta",
      vashya: "Vanchar",
   },
   {
      index: 20,
      name: "Uttara Ashadha",
      symbol: "🦦",
      animal: "Mongoose",
      animalGender: "Male",
      rashi: "Capricorn",
      rashiIndex: 9,
      lord: "Sun",
      lordIndex: 0,
      gana: "Manushya",
      varna: "Kshatriya",
      nadi: "Vata",
      vashya: "Manav",
   },
   {
      index: 21,
      name: "Shravana",
      symbol: "🐒",
      animal: "Monkey",
      animalGender: "Female",
      rashi: "Capricorn",
      rashiIndex: 9,
      lord: "Moon",
      lordIndex: 1,
      gana: "Deva",
      varna: "Shudra",
      nadi: "Kapha",
      vashya: "Manav",
   },
   {
      index: 22,
      name: "Dhanishta",
      symbol: "🦁",
      animal: "Lion",
      animalGender: "Female",
      rashi: "Aquarius",
      rashiIndex: 10,
      lord: "Mars",
      lordIndex: 3,
      gana: "Rakshasa",
      varna: "Vaishya",
      nadi: "Pitta",
      vashya: "Manav",
   },
   {
      index: 23,
      name: "Shatabhisha",
      symbol: "🐴",
      animal: "Horse",
      animalGender: "Female",
      rashi: "Aquarius",
      rashiIndex: 10,
      lord: "Rahu",
      lordIndex: 7,
      gana: "Rakshasa",
      varna: "Shudra",
      nadi: "Vata",
      vashya: "Jalchar",
   },
   {
      index: 24,
      name: "Purva Bhadrapada",
      symbol: "🦁",
      animal: "Lion",
      animalGender: "Male",
      rashi: "Pisces",
      rashiIndex: 11,
      lord: "Jupiter",
      lordIndex: 4,
      gana: "Manushya",
      varna: "Brahmin",
      nadi: "Kapha",
      vashya: "Manav",
   },
   {
      index: 25,
      name: "Uttara Bhadrapada",
      symbol: "🐄",
      animal: "Cow",
      animalGender: "Male",
      rashi: "Pisces",
      rashiIndex: 11,
      lord: "Saturn",
      lordIndex: 8,
      gana: "Manushya",
      varna: "Kshatriya",
      nadi: "Pitta",
      vashya: "Jalchar",
   },
   {
      index: 26,
      name: "Revati",
      symbol: "🐘",
      animal: "Elephant",
      animalGender: "Female",
      rashi: "Pisces",
      rashiIndex: 11,
      lord: "Mercury",
      lordIndex: 2,
      gana: "Deva",
      varna: "Shudra",
      nadi: "Vata",
      vashya: "Jalchar",
   },
];

// Planet friendship table for Graha Maitri (lordIndex: 0=Sun,1=Moon,2=Mercury,3=Mars,4=Jupiter,5=Venus,6=Ketu,7=Rahu,8=Saturn)
const PLANET_FRIENDSHIP = {
   0: { friends: [1, 3, 4], neutral: [2, 5], enemies: [6, 7, 8] }, // Sun
   1: { friends: [0, 2, 4], neutral: [3, 5, 8], enemies: [6, 7] }, // Moon
   2: { friends: [0, 5], neutral: [3, 4, 8], enemies: [1, 6, 7] }, // Mercury
   3: { friends: [0, 4], neutral: [2, 5, 6, 7], enemies: [1, 8] }, // Mars
   4: { friends: [0, 1, 3], neutral: [8], enemies: [2, 5, 6, 7] }, // Jupiter
   5: { friends: [2, 8], neutral: [3, 4, 6, 7], enemies: [0, 1] }, // Venus
   6: { friends: [3, 5], neutral: [4, 8], enemies: [0, 1, 2, 7] }, // Ketu
   7: { friends: [3, 5], neutral: [4, 8], enemies: [0, 1, 2, 6] }, // Rahu
   8: { friends: [2, 5, 7], neutral: [4], enemies: [0, 1, 3, 6] }, // Saturn
};

// Yoni compatibility matrix (animal → compatible animals)
const YONI_COMPATIBILITY = {
   Horse: {
      best: ["Horse"],
      friendly: ["Deer"],
      neutral: ["Elephant", "Sheep", "Cow"],
      enemy: ["Monkey", "Cat", "Tiger", "Mongoose"],
      worst: ["Buffalo", "Dog", "Rat", "Serpent", "Lion"],
   },
   Elephant: {
      best: ["Elephant"],
      friendly: ["Cow", "Buffalo"],
      neutral: ["Horse", "Monkey"],
      enemy: ["Lion", "Tiger"],
      worst: ["Rat", "Cat", "Dog", "Serpent", "Sheep", "Deer", "Mongoose"],
   },
   Sheep: {
      best: ["Sheep"],
      friendly: ["Monkey", "Deer"],
      neutral: ["Horse", "Cow"],
      enemy: ["Buffalo", "Tiger"],
      worst: ["Dog", "Rat", "Cat", "Serpent", "Elephant", "Lion", "Mongoose"],
   },
   Serpent: {
      best: ["Serpent"],
      friendly: [],
      neutral: ["Rat", "Deer", "Cow"],
      enemy: ["Dog", "Cat"],
      worst: [
         "Mongoose",
         "Horse",
         "Elephant",
         "Sheep",
         "Buffalo",
         "Tiger",
         "Monkey",
         "Lion",
      ],
   },
   Dog: {
      best: ["Dog"],
      friendly: [],
      neutral: ["Rat", "Buffalo"],
      enemy: ["Serpent", "Deer", "Sheep"],
      worst: [
         "Cat",
         "Tiger",
         "Monkey",
         "Horse",
         "Elephant",
         "Cow",
         "Lion",
         "Mongoose",
      ],
   },
   Cat: {
      best: ["Cat"],
      friendly: ["Rat"],
      neutral: ["Monkey", "Sheep"],
      enemy: ["Dog"],
      worst: [
         "Serpent",
         "Buffalo",
         "Tiger",
         "Horse",
         "Elephant",
         "Cow",
         "Deer",
         "Lion",
         "Mongoose",
      ],
   },
   Rat: {
      best: ["Rat"],
      friendly: ["Cat", "Serpent"],
      neutral: ["Dog", "Buffalo"],
      enemy: ["Monkey"],
      worst: [
         "Horse",
         "Elephant",
         "Sheep",
         "Cow",
         "Tiger",
         "Deer",
         "Lion",
         "Mongoose",
      ],
   },
   Cow: {
      best: ["Cow"],
      friendly: ["Elephant", "Buffalo"],
      neutral: ["Sheep", "Serpent", "Deer"],
      enemy: ["Tiger"],
      worst: ["Horse", "Rat", "Cat", "Dog", "Monkey", "Lion", "Mongoose"],
   },
   Buffalo: {
      best: ["Buffalo"],
      friendly: ["Cow", "Elephant"],
      neutral: ["Dog", "Rat"],
      enemy: ["Sheep", "Cat"],
      worst: [
         "Horse",
         "Serpent",
         "Tiger",
         "Monkey",
         "Deer",
         "Lion",
         "Mongoose",
      ],
   },
   Tiger: {
      best: ["Tiger"],
      friendly: ["Lion"],
      neutral: ["Horse", "Elephant"],
      enemy: ["Cow", "Buffalo", "Sheep"],
      worst: ["Rat", "Cat", "Dog", "Serpent", "Monkey", "Deer", "Mongoose"],
   },
   Deer: {
      best: ["Deer"],
      friendly: ["Horse", "Sheep"],
      neutral: ["Serpent", "Cow"],
      enemy: ["Dog"],
      worst: [
         "Rat",
         "Cat",
         "Elephant",
         "Buffalo",
         "Tiger",
         "Monkey",
         "Lion",
         "Mongoose",
      ],
   },
   Monkey: {
      best: ["Monkey"],
      friendly: ["Sheep"],
      neutral: ["Cat", "Elephant", "Horse"],
      enemy: ["Rat"],
      worst: [
         "Dog",
         "Serpent",
         "Cow",
         "Buffalo",
         "Tiger",
         "Deer",
         "Lion",
         "Mongoose",
      ],
   },
   Lion: {
      best: ["Lion"],
      friendly: ["Tiger"],
      neutral: ["Horse", "Elephant"],
      enemy: ["Elephant"],
      worst: [
         "Rat",
         "Cat",
         "Dog",
         "Serpent",
         "Sheep",
         "Cow",
         "Buffalo",
         "Deer",
         "Monkey",
         "Mongoose",
      ],
   },
   Mongoose: {
      best: ["Mongoose"],
      friendly: [],
      neutral: ["Rat", "Cat", "Dog"],
      enemy: [],
      worst: [
         "Serpent",
         "Horse",
         "Elephant",
         "Sheep",
         "Cow",
         "Buffalo",
         "Tiger",
         "Deer",
         "Monkey",
         "Lion",
      ],
   },
};

// Bhakoot (Rashi relation) scoring table [rashiA][rashiB] → points
// 0=Aries,1=Taurus,2=Gemini,3=Cancer,4=Leo,5=Virgo,6=Libra,7=Scorpio,8=Sag,9=Cap,10=Aqua,11=Pisces
const BHAKOOT_FRIENDLY = [
   [0, 6],
   [1, 7],
   [2, 8],
   [3, 9],
   [4, 10],
   [5, 11], // 2-12 pairs (bad)
   [0, 7],
   [1, 8],
   [2, 9],
   [3, 10],
   [4, 11],
   [5, 0], // 6-8 pairs (bad)
];

const getNakshatraByIndex = (idx) => NAKSHATRAS[idx % 27];

const getNakshatraFromLongitude = (moonLongitudeDeg) => {
   // Each nakshatra = 360/27 = 13.333... degrees
   const nakshatraSpan = 360 / 27;
   const index = Math.floor(moonLongitudeDeg / nakshatraSpan) % 27;
   return NAKSHATRAS[index];
};

module.exports = {
   NAKSHATRAS,
   PLANET_FRIENDSHIP,
   YONI_COMPATIBILITY,
   BHAKOOT_FRIENDLY,
   getNakshatraByIndex,
   getNakshatraFromLongitude,
};
